# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 708ca8219f7a74a7521712b16ee4c1bfd33c2ad9e8711dbe7b43a5456bc3846b5db2abf26c5152d3d524c1d76a8ca628c944b1beb9d1ab456ebd4b49f331af44

test:
  secret_key_base: a8b87cd0578f73a24e08c258a4f1c702d4a9aade3012aa860c67167e52107565abf9c50c6ffc90d0db48022b657540e8fd22d8200edff2200c224573990a2e38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
